############################################################################
# Copyright (c) 2025 by the Beatnik authors                                #
# All rights reserved.                                                     #
#                                                                          #
# This file is part of the Beatnik library. Beatnik is distributed under a #
# BSD 3-clause license. For the licensing terms see the LICENSE file in    #
# the top-level directory.                                                 #
#                                                                          #
# SPDX-License-Identifier: BSD-3-Clause                                    #
############################################################################
#
# Committed per-system profile defaults for tuolumne. Sourced by
# scripts/lib/beatnik_env.sh; DO NOT source this directly.
#
# These values reproduce what tuolumne scripts and docs hardcoded before the
# profile mechanism existed, so a fresh checkout works with zero configuration.
# To change them for YOUR checkout, create scripts/tuolumne/profile.local.sh
# (gitignored) — do not edit this file for a personal preference.
#
# Every assignment uses ${VAR:=...} so an exported environment variable and
# anything already set by an earlier source both win over these defaults.
############################################################################

# Build mode. Tuolumne's historical and canonical path is spack: the env
# provides dependencies AND builds/installs beatnik itself via
# `spack develop` + `spack install`, putting binaries on PATH.
# Set to "manual" in profile.local.sh to hand-compile out-of-tree instead.
: "${BEATNIK_BUILD_MODE:=spack}"

# Development environment — builds and iterative work. Rebuilt frequently.
: "${BEATNIK_SPACK_ENV:=${HOME}/spack_envs/tuolumne_beatnik}"

# Production environment — large runs that may sit in the queue for hours.
# Pinning a queued job here means dev rebuilds cannot break it.
: "${BEATNIK_SPACK_PROD_ENV:=${HOME}/spack_envs/tuolumne_beatnik_production}"

# Out-of-tree cmake build directory, used only when BEATNIK_BUILD_MODE=manual.
: "${BEATNIK_BUILD_DIR:=${BEATNIK_REPO}/build-tuolumne}"
