############################################################################
# Copyright (c) 2025 by the Beatnik authors                                #
# All rights reserved.                                                     #
#                                                                          #
# This file is part of the Beatnik library. Beatnik is distributed under a #
# BSD 3-clause license. For the licensing terms see the LICENSE file in    #
# the top-level directory.                                                 #
#                                                                          #
# SPDX-License-Identifier: BSD-3-Clause                                    #
############################################################################
#
# Committed per-system profile FALLBACKS for tuolumne. Sourced by
# scripts/lib/beatnik_env.sh; DO NOT source this directly.
#
# SCOPE — read this before editing.
#
# This file is committed, so everything in it is a claim about *tuolumne as a
# machine*, true for every checkout on it. It is NOT a claim about any
# particular checkout, and it is NOT a policy.
#
# The build mode, the specific environment a checkout is developed into, and the
# build directory are all properties of an INSTANCE of this repository, not of
# the machine: two clones side by side on tuolumne can legitimately differ, one
# `spack develop`ed into an env and one hand-built out-of-tree. Those belong in
# scripts/tuolumne/profile.local.sh, which is gitignored precisely because it
# describes one checkout.
#
# So the values below are only a **fallback so that a fresh clone runs with zero
# configuration**, chosen as the most common setup on this machine. An agent or
# user starting work in a checkout that has no profile.local.sh should confirm
# the mode and write one rather than assume these (see CLAUDE.md "Session-start
# flow"). Scripts, by contrast, deliberately fall through to these values so
# batch jobs never block on a prompt.
#
# Every assignment uses ${VAR:=...} so an exported environment variable and
# anything set by profile.local.sh both win over these fallbacks. The resolver
# reports which source won in BEATNIK_PROFILE_SOURCE.
#
# Do not edit this file to record a personal preference — that would impose one
# checkout's choice on every clone on the machine. Edit profile.local.sh.
############################################################################

# Fallback build mode. `spack` is the most common setup on tuolumne — the env
# provides dependencies AND builds/installs beatnik itself via `spack develop`
# + `spack install`, putting binaries on PATH.
#
# Not a mandate: a checkout that hand-compiles out-of-tree sets
# BEATNIK_BUILD_MODE=manual in its own profile.local.sh, and the resolver, the
# gate wrapper and the batch template all handle both modes. What is forbidden
# is *mixing* them — see CLAUDE.md, where the build rules are scoped to the
# active mode rather than to the repository.
: "${BEATNIK_BUILD_MODE:=spack}"

# Development environment — builds and iterative work. Rebuilt frequently.
# A checkout developed into a different env overrides this in profile.local.sh.
: "${BEATNIK_SPACK_ENV:=${HOME}/spack_envs/tuolumne_beatnik}"

# Production environment — large runs that may sit in the queue for hours.
# Pinning a queued job here means dev rebuilds cannot break it.
: "${BEATNIK_SPACK_PROD_ENV:=${HOME}/spack_envs/tuolumne_beatnik_production}"

# Out-of-tree cmake build directory, used only when BEATNIK_BUILD_MODE=manual.
# Derived from BEATNIK_REPO so two clones do not collide on one build tree.
: "${BEATNIK_BUILD_DIR:=${BEATNIK_REPO}/build-tuolumne}"
