# LLNL Tioga Spack Environment

spack:
  packages:
    all:
      variants: +rocm amdgpu_target=gfx90a
      providers:
        blas: [openblas, cray-libsci@24.03.0]
        lapack: [openblas, cray-libsci@24.03.0]
        mpi: [cray-mpich]
        scalapack: [netlib-scalapack]
      target: [zen3]
    cray-libsci:
      buildable: false
      externals:
      - modules:
        - cray-libsci/24.03.0
        spec: cray-libsci@24.03.0
      version: [24.03.0]
    cray-mpich:
      buildable: false
      externals:
      - spec: cray-mpich@8.1.30 %gcc
        prefix: /opt/cray/pe/mpich/8.1.30/ofi/gnu/11.2
        extra_attributes:
          accel: amd_gfx90a
          gtl_lib_path: /opt/cray/pe/mpich/8.1.30/gtl
          gtl_cutoff_size: 4096
          fi_cxi_ats: 0
      - spec: cray-mpich@8.1.30 %rocmcc@6
        prefix: /opt/cray/pe/mpich/8.1.30/ofi/rocm-compiler/6.0
        extra_attributes:
          accel: amd_gfx90a
          gtl_lib_path: /opt/cray/pe/mpich/8.1.30/gtl
          gtl_cutoff_size: 4096
          fi_cxi_ats: 0
      - spec: cray-mpich@8.1.30 %cce@18
        prefix: /opt/cray/pe/mpich/8.1.30/ofi/cray/18.0
        extra_attributes:
          accel: amd_gfx90a
          gtl_lib_path: /opt/cray/pe/mpich/8.1.30/gtl
          gtl_cutoff_size: 4096
          fi_cxi_ats: 0
    fftw:
      buildable: true
      variants: precision=float,double,long_double
    hdf5:
      buildable: false
      externals:
      - spec: hdf5@1.12.2 +mpi %rocmcc@5
        prefix: /opt/cray/pe/hdf5-parallel/1.12.2.9/AMD/5.0
      - spec: hdf5@1.14.3 +mpi %gcc@12
        prefix: /opt/cray/pe/hdf5-parallel/1.14.3/gnu/12.2
      - spec: hdf5@1.12.2 +mpi %cce
        prefix: /opt/cray/pe/hdf5-parallel/1.12.2.11/crayclang/17.0
    hip:
      buildable: false
      externals:
      - spec: hip@6.1.2
        prefix: /opt/rocm-6.1.2
        extra_attributes:
          compilers:
            hip: /opt/rocm-6.1.2/bin/hipcc
    hip-rocclr:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2/rocclr
        spec: hip-rocclr@6.1.2 ^hsa-rocr-dev@6.1.2
    hipblas:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: hipblas@6.1.2
    hipcub:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: hipcub@6.1.2
    hipfft:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: hipfft@6.1.2
    hipfort:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: hipfort@6.1.2
    hipify-clang:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: hipify-clang@6.1.2
    hipsparse:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: hipsparse@6.1.2
    hsa-rocr-dev:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: hsa-rocr-dev@6.1.2
    hsakmt-roct:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: hsakmt-roct@6.1.2
    libfabric:
      buildable: true
      externals:
      - prefix: /opt/cray/libfabric/2.1
        spec: libfabric@2.1
      - prefix: /opt/cray/libfabric/2.0
        spec: libfabric@2.0
      - prefix: /opt/cray/libfabric/1.7.2-llnl
        spec: libfabric@1.7.2
      version:
      - '2.1'
      - '2.0'
      - 1.7.2
      variants: fabrics=rxm,sockets,tcp,udp
    libtool:
      buildable: true
      version: [2.4.6]
    llvm-amdgpu:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2/llvm
        spec: llvm-amdgpu@6.1.2
    m4:
      buildable: true
      version: [1.4.18]
    miopen-hip:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: miopen-hip@6.1.2
    ncurses:
      buildable: false
      externals:
      - prefix: /usr
        spec: ncurses@5.9
      version:
      - '5.9'
    openssh:
      buildable: false
      externals:
      - prefix: /usr
        spec: openssh@8.4
      version:
      - '8.4'
    openssl:
      buildable: false
      externals:
      - spec: openssl@1.1.1-os
        prefix: /usr
      version: [1.1.1-os]
    parallel-netcdf:
      buildable: true
      variants: +cxx+fortran
      version: []
    petsc:
      variants: +batch
    raja:
      variants: ~exercises~examples~tests~openmp~rocm
    rccl:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rccl@6.1.2
    rocalution:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocalution@6.1.2
    rocblas:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocblas@6.1.2
    rocfft:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocfft@6.1.2
    rocm-clang-ocl:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocm-clang-ocl@6.1.2
    rocm-cmake:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocm-cmake@6.1.2
    rocm-device-libs:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocm-device-libs@6.1.2
    rocm-gdb:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocm-gdb@6.1.2
    rocm-opencl:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2/opencl
        spec: rocm-opencl@6.1.2
    rocm-opencl-runtime:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2/opencl
        spec: rocm-opencl-runtime@6.1.2
    rocm-openmp-extras:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2/llvm
        spec: rocm-openmp-extras@6.1.2
    rocm-smi:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2/rocm_smi
        spec: rocm-smi@6.1.2
    rocm-smi-lib:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2/rocm_smi
        spec: rocm-smi-lib@6.1.2
    rocminfo:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocminfo@6.1.2
    rocprim:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocprim@6.1.2
    rocprofiler-dev:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocprofiler-dev@6.1.2
    rocrand:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocrand@6.1.2
    rocsolver:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocsolver@6.1.2
    rocsparse:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocsparse@6.1.2
    rocthrust:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: rocthrust@6.1.2
    roctracer-dev:
      buildable: false
      externals:
      - prefix: /opt/rocm-6.1.2
        spec: roctracer-dev@6.1.2
    slurm:
      buildable: false
      externals:
      - prefix: /usr
        spec: slurm@21.08.0
      version: [21.08.0]
    silo:
      variants: ~hzip
    sundials:
      variants: ~examples~examples-install
    tcsh:
      buildable: false
      externals:
      - prefix: /usr
        spec: tcsh@6.20.00
      version: [6.20.00]
  config:
    verify_ssl: true
    install_missing_compilers: false
    checksum: true
    dirty: false
    build_language: C
    build_jobs: 24
    ccache: false
    db_lock_timeout: 120
    package_lock_timeout: null
    shared_linking:
      type: rpath
      bind: false
    allow_sgid: true
    concretizer: clingo
    locks: true
    suppress_gpg_warnings: false
    connect_timeout: 10
    test_stage: ~/.spack/test
    concretization: unify
  compilers:
  - compiler:
      spec: cce@=18.0.0
      paths:
        cc: /usr/tce/packages/cce-tce/cce-18.0.0/bin/craycc
        cxx: /usr/tce/packages/cce-tce/cce-18.0.0/bin/crayCC
        f77: /usr/tce/packages/cce-tce/cce-18.0.0/bin/crayftn
        fc: /usr/tce/packages/cce-tce/cce-18.0.0/bin/crayftn
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths:
      - /opt/cray/pe/gcc-libs
  - compiler:
      spec: rocmcc@6.1.2
      paths:
        cc: /usr/tce/packages/rocmcc-tce/rocmcc-6.1.2/bin/amdclang
        cxx: /usr/tce/packages/rocmcc-tce/rocmcc-6.1.2/bin/amdclang++
        f77: /usr/tce/packages/rocmcc-tce/rocmcc-6.1.2/bin/amdflang
        fc: /usr/tce/packages/rocmcc-tce/rocmcc-6.1.2/bin/amdflang
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@12.2.1
      paths:
        cc: /usr/tce/packages/gcc/gcc-12.2.1-magic/bin/gcc
        cxx: /usr/tce/packages/gcc/gcc-12.2.1-magic/bin/g++
        f77: /usr/tce/packages/gcc/gcc-12.2.1-magic/bin/gfortran
        fc: /usr/tce/packages/gcc/gcc-12.2.1-magic/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
  specs:
  - beatnik@develop +rocm amdgpu_target=gfx90a build_type=RelWithDebInfo %cce
  develop:
    beatnik:
      spec: beatnik@develop +rocm amdgpu_target=gfx90a build_type=RelWithDebInfo %cce
