# This spack environment assumes that the gcc/11.2.0 and the cmake/3.26.3 modules are always loaded.
# To use this environment spec, follow the directions in configs/README.md 

spack:
  specs:
  - blt
  - cuda@11.7
  - ucx +ib_hw_tm +verbs +gdrcopy
  - openmpi @4.1: +cuda cuda_arch=35 fabrics=ucx
  - heffte +cuda cuda_arch=35
  - kokkos @4: +hwloc +cuda +cuda_lambda +wrapper cuda_arch=35
  - cabana @master +cajita +heffte +mpi +cuda
  - silo@4.11 +mpi
  concretizer:
    unify: true
  view: true
