spack:
  specs:
  - matrix:
    - - cuda@11.1.1
      - spectrum-mpi@rolling-release
      - heffte +fftw +cuda cuda_arch=70
      - kokkos +hwloc +cuda +cuda_lambda +wrapper cuda_arch=70
      - cabana @master +grid +heffte +mpi +cuda +arborx cuda_arch=70
    - ['%gcc@8.3.1']
  - silo@4.11 +mpi
  - hdf5 +mpi
  - blt
  concretizer:
    unify: true
  view: true
  packages:
    spectrum-mpi:
      externals:
        - spec: spectrum-mpi@rolling-release
          prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/
      buildable: False
  compilers:
  - compiler:
      spec: clang@=12.0.1
      paths:
        cc: /usr/tcetmp/bin/clang
        cxx: /usr/tcetmp/bin/clang++
        f77: null
        fc: null
      flags: {}
      operating_system: rhel7
      target: ppc64le
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: clang@=6.0.0
      paths:
        cc: /usr/tcetmp/bin/clang-archer
        cxx: null
        f77: null
        fc: null
      flags: {}
      operating_system: rhel7
      target: ppc64le
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=4.8.5
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: rhel7
      target: ppc64le
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=4.9.3
      paths:
        cc: /usr/tcetmp/bin/gcc
        cxx: /usr/tcetmp/bin/g++
        f77: /usr/tcetmp/bin/gfortran
        fc: /usr/tcetmp/bin/gfortran
      flags: {}
      operating_system: rhel7
      target: ppc64le
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=8.3.1
      paths:
        cc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gcc
        cxx: /usr/tce/packages/gcc/gcc-8.3.1/bin/g++
        f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
        fc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      flags: {}
      operating_system: rhel7
      target: ppc64le
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: xl@=16.1
      paths:
        cc: /usr/tcetmp/bin/xlc
        cxx: /usr/tcetmp/bin/xlC
        f77: null
        fc: null
      flags:
        fflags: -qzerosize
      operating_system: rhel7
      target: ppc64le
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: xl_r@=16.1
      paths:
        cc: /usr/tcetmp/bin/xlc_r
        cxx: /usr/tcetmp/bin/xlC_r
        f77: null
        fc: null
      flags:
        fflags: -qzerosize
      operating_system: rhel7
      target: ppc64le
      modules: []
      environment: {}
      extra_rpaths: []
